#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
linter_exit_code=1
cd client && npm run pretty
npm run lint
linter_exit_code=$?
if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Linter errors found in client ( ͡ಥ ͜ʖ ͡ಥ)${NC}"
  exit 1
else
  echo "${GREEN} ✔ Eslint did not find any errors in client [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]${NC}"
fi
cd ../server && npm run pretty
npm run lint
linter_exit_code=$?
if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Linter errors found in server ( ͡ಥ ͜ʖ ͡ಥ)${NC}"
  exit 1
else
  echo "${GREEN} ✔ Eslint did not find any errors in server [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]${NC}"
  exit 0
fi
